import os

from dotenv import load_dotenv

load_dotenv()

API_KEY = os.getenv('BINANCE_API_KEY')
SECRET_KEY = os.getenv('BINANCE_SECRET_KEY')

SYMBOL = 'BTCUSDT'
TRADE_SYMBOL = 'BTCUSDT'
SIDE_BUY = 'BUY'
SIDE_SELL = 'SELL'
ORDER_TYPE_MARKET = 'MARKET'
ORDER_TYPE_LIMIT = 'LIMIT'
TRADE_QUANTITY = 0.001
MAX_POSITION = 0.005
MAX_TRADE_QUANTITY = 0.002
STOP_LOSS = 0.98
TAKE_PROFIT = 1.02
